version: '3'
services:
  web-nginx:
    image: nginx:stable-alpine
    container_name: web-nginx
    volumes:
      - "./www:/usr/share/nginx/html:rw"
      - "./log:/var/log/nginx"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:rw"
    ports:
      - "8080:80"


  web-php:
    image: php:fpm-alpine
    container_name: web-php
    build:
      ./www
    volumes:
      - "./www:/script:rw"


  gotenberg:
    image: thecodingmachine/gotenberg:5
    ports:
      - "4000:4000"
    environment:
      DEFAULT_LISTEN_PORT: '4000'
