services:
  web-nginx:
    image: nginx:stable-alpine
    container_name: web-nginx
    volumes:
      - "./www:/usr/share/nginx/html:ro"
      - "./log:/var/log/nginx"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8080:80"

  web-php:
    image: php:fpm-alpine
    container_name: web-php
    volumes:
      - "./www:/script:ro"
